version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "ci"
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/bindings/node"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "node"
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/bindings/python"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "python"
      - "dependencies"
